services:
  - type: web
    name: money-manager-app
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mm_production
          property: connectionString
databases:
  - name: mm_production
    plan: free

